# Generated by Django 5.1.2 on 2024-10-10 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# noinspection SpellCheckingInspection
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # noinspection SpellCheckingInspection
    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('kalem', models.CharField(choices=[('Market', 'Market'), ('Araba', 'Araba'), ('Yakıt', 'Yakıt'), ('Ulaşım', 'Ulaşım'), ('Restoran', 'Restoran'),
                                                    ('Cafe/Pastane', 'Cafe/Pastane'), ('Kozmetik/Eczane/Gözlük', 'Kozmetik/Eczane/Gözlük'), ('Giyim/Ayakkabı/Çanta', 'Giyim/Ayakkabı/Çanta'), ('Sigorta-araba', 'Sigorta-araba'), ('Sigorta-sağlık/TSS', 'Sigorta-sağlık/TSS'),
                                                    ('Sigorta-mal', 'Sigorta-mal'), ('Online-abonelik', 'Online-abonelik'), ('Online-hizmet', 'Online-hizmet'), ('Online-alışveriş', 'Online-alışveriş'), ('Nalbur/Beyazeşya', 'Nalbur/Beyazeşya'), ('Ev-Reji', 'Ev-Reji'), ('Ev-Internet', 'Ev-Internet'), ('TV-abonelik', 'TV-abonelik'), ('Hediye', 'Hediye'), ('Kedi', 'Kedi'), ('Diğer', 'Diğer')], max_length=50)),
                ('kart', models.CharField(choices=[('Miles', 'Miles'), ('World', 'World'), ('Bonus', 'Bonus'), ('Maximum', 'Maximum'), ('Troy', 'Troy'), ('Enpara', 'Enpara'), ('Nakit', 'Nakit')], max_length=20)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
