# Generated by Django 5.1.2 on 2024-10-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarcamaApp', '0002_alter_expense_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='bilgi',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expense_images/', verbose_name='Resim'),
        ),
    ]
