runtime: python39

env_variables:
  DJANGO_SETTINGS_MODULE: "harcamalar.settings"
  GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"
  SECRET_KEY: "django-insecure-bf+$qnfdda#&m8=mfm#sxdnavwg5agk)6wsn=4tl8kyzyt=&c5"
  DEBUG: "True"

handlers:
- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: auto
  secure: always

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
