# Generated by Django 4.2.16 on 2024-10-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harcama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalem', models.CharField(choices=[('Market', 'Market'), ('Araba', 'Araba'), ('Yakıt', 'Yakıt'), ('Ulaşım', 'Ulaşım'), ('Restoran', 'Restoran'), ('Cafe/Pastane', 'Cafe/Pastane'), ('Kozmetik/Eczane/Gözlük', 'Kozmetik/Eczane/Gözlük'), ('Giyim/Ayakkabı/Çanta', 'Giyim/Ayakkabı/Çanta'), ('Sigorta-araba', 'Sigorta-araba'), ('Sigorta-sağlık/TSS', 'Sigorta-sağlık/TSS'), ('Sigorta-mal', 'Sigorta-mal'), ('Online-abonelik', 'Online-abonelik'), ('Online-hizmet', 'Online-hizmet'), ('Online-alışveriş', 'Online-alışveriş'), ('Nalbur/Beyazeşya', 'Nalbur/Beyazeşya'), ('Ev-Reji', 'Ev-Reji'), ('Ev-Internet', 'Ev-Internet'), ('TV-abonelik', 'TV-abonelik'), ('Hediye', 'Hediye'), ('Diğer', 'Diğer')], max_length=50)),
                ('odeme_turu', models.CharField(choices=[('kredikartı', 'Kredi Kartı'), ('nakit', 'Nakit')], max_length=20)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
